### ISSUE TITLE
Not working with public feed

### ISSUE THREAD

**Issue by clairernovotny** [renevanosnabrugge/vsts-promotepackage-task#29]
Trying to promote a package on a public feed is not working. I get this:

```
2019-08-01T15:57:18.3076627Z ##[section]Starting: Promote package to Release View
2019-08-01T15:57:18.3181304Z ==============================================================================
2019-08-01T15:57:18.3181398Z Task : Promote package to Release View
2019-08-01T15:57:18.3181468Z Description : Promotes a package to a Release View in VSTS Package Management
2019-08-01T15:57:18.3181546Z Version : 2.0.2
2019-08-01T15:57:18.3181878Z Author : Rene van Osnabrugge
2019-08-01T15:57:18.3181979Z Help : Version: 2.0.2. [More Information](https://github.com/renevanosnabrugge/vsts-promotepackage-task/wiki)
2019-08-01T15:57:18.3182057Z ==============================================================================
2019-08-01T15:57:19.6479549Z Promoting package(s) by reading metadata from package file(s) matching pattern '**/*.nupkg !**/*.symbols.nupkg' from root directory 'D:\a\r1\a\CI\artifacts'
2019-08-01T15:57:20.1552760Z Matching paths found:
2019-08-01T15:57:20.1553159Z D:\a\r1\a\CI\artifacts\System.Interactive.4.0.0-preview.7.build.829.nupkg D:\a\r1\a\CI\artifacts\System.Interactive.Async.4.0.0-preview.7.build.829.nupkg D:\a\r1\a\CI\artifacts\System.Interactive.Async.Providers.4.0.0-preview.7.build.829.nupkg D:\a\r1\a\CI\artifacts\System.Interactive.Providers.4.0.0-preview.7.build.829.nupkg D:\a\r1\a\CI\artifacts\System.Linq.Async.4.0.0-preview.7.build.829.nupkg D:\a\r1\a\CI\artifacts\System.Linq.Async.Queryable.4.0.0-preview.7.build.829.nupkg
2019-08-01T15:57:20.3510522Z Promoting version of package from feed 5afc77bd-23b4-46f8-b725-40ebedab630c to view Prerelease
2019-08-01T15:57:20.6963229Z ##[error]Unhandled exception while reading feed 5afc77bd-23b4-46f8-b725-40ebedab630c
System.Net.WebException: The remote server returned an error: (404) Not Found.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()at Get-FeedId, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.2\vsts-promotepackage-task.ps1: line 46
at Set-PackageQuality, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.2\vsts-promotepackage-task.ps1: line 135
at Run, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.2\vsts-promotepackage-task.ps1: line 280
at <ScriptBlock>, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.2\vsts-promotepackage-task.ps1: line 286
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
2019-08-01T15:57:20.7273286Z ##[section]Finishing: Promote package to Release View
```

**Comment by NightOwl888** [comment]
I suspect this is probably the same issue as #27, for which I have already submitted a PR #28. What is the XML namespace in the `.nuspec` file that is inside of your `.nupkg` files?

**Comment by onovotny** [comment]
The nuspec looks like this

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
  <metadata minClientVersion="2.12">
    <id>System.Interactive</id>
    <version>4.0.0-preview.7.build.829</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <license type="expression">Apache-2.0</license>
    <projectUrl>https://github.com/dotnet/reactive</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/dotnet/reactive/0f837d11385cfaf575861ccc5a5fbcafb22d888f/Rx.NET/Resources/Artwork/Logo.png</iconUrl>
    <description>Interactive Extensions Main Library used to express queries over enumerable sequences.</description>
    <copyright>Copyright (c) .NET Foundation and Contributors.</copyright>
    <tags>Ix Interactive Extensions Enumerable</tags>
    <repository type="git" url="https://github.com/dotnet/reactive" commit="62ca8775f8c0381999656207c92675e4a3b97fdb" />
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard1.0">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
  </metadata>
</package>
```

**Comment by onovotny** [comment]
After the XML namespace issue, it's still not working:

```
2019-08-19T15:56:54.2829662Z Promoting version 2.0.41 of package MSBuild.Sdk.Extras from feed 3773a966-220c-4410-a273-f6d772116a25 to view Prerelease
2019-08-19T15:56:54.7703355Z ##[error]Unhandled exception while reading feed 3773a966-220c-4410-a273-f6d772116a25
System.Net.WebException: The remote server returned an error: (404) Not Found.
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()at Get-FeedId, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.4\vsts-promotepackage-task.ps1: line 46
at Set-PackageQuality, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.4\vsts-promotepackage-task.ps1: line 135
at Run, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.4\vsts-promotepackage-task.ps1: line 279
at <ScriptBlock>, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.4\vsts-promotepackage-task.ps1: line 285
at <ScriptBlock>, <No file>: line 1
```

**Comment by NightOwl888** [comment]
Hmm, this doesn't happen to be on a private on-site Azure DevOps server would it? Do note that it is not currently supported, although I don't imagine it would take much work to support it - it is just a matter of working out the URL schemes that are used, I think.

**Comment by onovotny** [comment]
No, this is a public feed.

**Comment by NightOwl888** [comment]
Which domain is it hosted on?

1. `dev.azure.com`
2. `vsrm.dev.azure.com`
3. `<org>.visualstudio.com`
4. None of the above

**Comment by onovotny** [comment]
`dev.azure.com`.

You can see it here: https://dev.azure.com/onovotny/GitBuilds/_packaging?_a=package&feed=MSBuildSdkExtras&package=MSBuild.Sdk.Extras&protocolType=NuGet&version=2.0.41

**Comment by NightOwl888** [comment]
One other thing comes to mind - semver metadata, which probably needs some URL escaping to be able to work. What is the version number you are trying to promote? Does it contain a `+` or something else that needs URL escaping?

**Comment by onovotny** [comment]
In this case, no SemVer. Just 2.0.41. The log shows that it parsed the correct version.

What I do notice is that the "Views" dropdown in the Task editor doesn't populate.

**Comment by NightOwl888** [comment]
Looks like Microsoft botched this one. They released a new API version, `5.1-preview.1` which has added a `{project}` segment to the URL.

```
Version 5.1-preview.1:
PATCH https://feeds.dev.azure.com/{organization}/{project}/_apis/packaging/Feeds/{feedId}/views/{viewId}?api-version=5.1-preview.1

Version 
PATCH https://feeds.dev.azure.com/{organization}/_apis/packaging/Feeds/{feedId}/views/{viewId}?api-version=5.0-preview.1
```

https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/update%20feed%20view?view=azure-devops-rest-5.0
https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/update%20feed%20view?view=azure-devops-rest-5.1

We are passing the API version as `5.0-preview.1`, which is hard coded in the task, but the new API version seems to be ignoring it.

**Comment by onovotny** [comment]
Is the fix to increase the api version in the task?

**Comment by renevanosnabrugge** [comment]
Worth a try...

Verstuurd vanaf mijn iPhone

Op 19 aug. 2019 om 18:56 heeft Oren Novotny <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Is the fix to increase the api version in the task?

**Comment by NightOwl888** [comment]
I suggest increase the version number and also fix the base URL behavior to include the extra parameter. It is unclear if the API affects the `visualstudio.com` domain in some way.

**Comment by NightOwl888** [comment]
Or I suppose another "fix" is to report and wait for Microsoft to patch it. No doubt others will be complaining about this as well, because it is a breaking change.

**Comment by onovotny** [comment]
I'm not sure what the breaking change is?

Public feeds require the project in it as thy're project-scoped. Guess that means they require 5.1? what's breaking?

**Comment by NightOwl888** [comment]
APIs are *always* supposed to build in backward compatible behavior. That is the reason for the specification of `5.0-preview.1` in the URL, to make sure that if a new version is released that the specified version's behavior is respected.

I don't know if Microsoft is considering the fact that the version is "preview" as a license to break this rule, but no doubt a lot of code is now broken because of this API update. I would expect that if this was an intentional break, the documentation would have lots of warnings in it that this is in preview and there could be breaking changes ahead.

**Comment by onovotny** [comment]
I'm sorry if I'm dense and not following.... it seems like public feeds cannot be represented with the 5.0 api. Nothing has changed otherwise.

What am I missing? I can raise this with the team, I'm just trying to understand what the expected vs actual behavior is.

**Comment by NightOwl888** [comment]
> it seems like public feeds cannot be represented with the 5.0 api

**Comment by NightOwl888** [comment]
> it seems like public feeds cannot be represented with the 5.0 api

Well, you may be right. Normally the version number is at the beginning of the URL (i.e. a folder) so new versions can be deployed side-by-side with the old ones. That way if the rest of the URL structure changes, it doesn't break.

```
version 1.0:
https://www.somewhere.com/api/1.0/{organization}/feed

version 1.1:
https://www.somewhere.com/api/1.1/{organization}/{project}/feed
```

There is nothing wrong with using a URL parameter to do it, as long as you build the backward compatible behavior into the *new* version. It is expected that if you pass in the old URL, it will still work after the next version is deployed.

```
// Used to work, now doesn't:
https://feeds.dev.azure.com/{organization}/_apis/packaging/Feeds/{feedId}/views/{viewId}?api-version=5.0-preview.1

// (probably) works after the update:
https://feeds.dev.azure.com/{organization}/{project}/_apis/packaging/Feeds/{feedId}/views/{viewId}?api-version=5.1-preview.1
```

Humans don't call APIs, programs do. In order to keep those programs from suddenly breaking for no apparent reason, those who maintain the APIs must make sure backward compatibility is respected.

I am not saying that we shouldn't update to the new API version, but we shouldn't be forced to do it because of a break, we should be able to do it on our own schedule.

**Comment by onovotny** [comment]
> I am not saying that we shouldn't update to the new API version, but we shouldn't be forced to do it because of a break, we should be able to do it on our own schedule.

I guess it depends on definition of break. Public feeds are considered a new feature, so no existing thing could be thought of supporting them.

**Comment by renevanosnabrugge** [comment]
I agree. If it worked with previous version the back compat should be fixed.

We can use the other url for now. But this is not how an api should work.

Verstuurd vanaf mijn iPhone

Op 19 aug. 2019 om 20:14 heeft Oren Novotny <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I am not saying that we shouldn't update to the new API version, but we shouldn't be forced to do it because of a break, we should be able to do it on our own schedule.

I guess it depends on definition of break. Public feeds are considered a new feature, so no existing thing could be thought of supporting them.

**Comment by ferwe** [comment]
So what is the next step in this issue?
Fixing the url in the extension or something else? 
:)

**Comment by pogosoftware** [comment]
Any progress? I have the latest version of the plugin and still can't publish packages to my project feed.

**Comment by renevanosnabrugge** [comment]
I raised an issue with the product team. There is a work around. Make the feed organization wide.

As fix I am thinking of getting all feed details in the powershell script. But not much time to implement. PR welcome :)



Verstuurd vanaf mijn iPhone

Op 24 dec. 2019 om 19:35 heeft Przemysław Pogorzelec <notifications@github.com> het volgende geschreven:

﻿

Any progress? I have the latest version of the plugin and still can't publish packages to my project feed.

**Comment by itsjusth** [comment]
Project-scoped feeds are the default for new Feeds created in ADO: https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops

It is not possible to change the scope to Organization.

**Comment by renevanosnabrugge** [comment]
should be fixed in the latest version

**Comment by jjburr** [comment]
This still appears to be an issue, when using the task and selecting any public feed nothing will populate :(

![image](https://user-images.githubusercontent.com/31635161/80663401-fe7e7400-8ae7-11ea-8cd2-a337d921a06a.png)

**Comment by renevanosnabrugge** [comment]
fixed in https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/54 .
